#!/bin/bash
ls -la
total 20
drwxr-xr-x 2 root root 122 Mar 15 06:32 .
drwxr-xr-x 4 root root  60 Mar 15 05:03 ..
-rw-r--r-- 1 root root  16 Mar 15 05:00 0-current_working_directory
-rw-r--r-- 1 root root  80 Mar 15 06:25 1-listit
-rw-r--r-- 1 root root  21 Mar 15 05:20 2-bring_me_home
-rw-r--r-- 1 root root 317 Mar 15 06:18 3-listfiles
-rw-r--r-- 1 root root  19 Mar 15 06:32 4-listmorefiles
